from django.urls import path
from . import views

urlpatterns = [

    # path("get_attendance", views.get_attendance, name='get_attendance'),
    # path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("", views.admin_home, name='admin_home'),
    path("staff/add", views.add_staff, name='add_staff'),
    path("course/add", views.add_course, name='add_course'),
    path("send_student_notification/", views.send_student_notification,
         name='send_student_notification'),
    path("send_staff_notification/", views.send_staff_notification,
         name='send_staff_notification'),
    path("add_session/", views.add_session, name='add_session'),
    path("admin_notify_student", views.admin_notify_student,
         name='admin_notify_student'),
    path("admin_notify_staff", views.admin_notify_staff,
         name='admin_notify_staff'),
    # path("admin_view_profile", views.admin_view_profile,
    #      name='admin_view_profile'),
    path("check_email_availability", views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         views.edit_session, name='edit_session'),
    path("student/view/feedback/", views.student_feedback_message,
         name="student_feedback_message",),
    path("staff/view/feedback/", views.staff_feedback_message,
         name="staff_feedback_message",),
    path("student/view/leave/", views.view_student_leave,
         name="view_student_leave",),
    path("staff/view/leave/", views.view_staff_leave, name="view_staff_leave",),
    path("attendance/view/", views.admin_view_attendance,
         name="admin_view_attendance",),
    path("attendance/fetch/", views.get_admin_attendance,
         name='get_admin_attendance'),
    path("student/add/", views.add_student, name='add_student'),
    path("subject/add/", views.add_subject, name='add_subject'),
    path("staff/manage/", views.manage_staff, name='manage_staff'),
    path("student/manage/", views.manage_student, name='manage_student'),
    path("course/manage/", views.manage_course, name='manage_course'),
    path("subject/manage/", views.manage_subject, name='manage_subject'),
    path("staff/edit/<int:staff_id>", views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         views.delete_staff, name='delete_staff'),

    path("course/delete/<int:course_id>",
         views.delete_course, name='delete_course'),

    path("subject/delete/<int:subject_id>",
         views.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>",
         views.delete_session, name='delete_session'),

    path("student/delete/<int:student_id>",
        views.delete_student, name='delete_student'),
    path("student/edit/<int:student_id>",
         views.edit_student, name='edit_student'),
    path("course/edit/<int:course_id>",
         views.edit_course, name='edit_course'),
    path("subject/edit/<int:subject_id>",
         views.edit_subject, name='edit_subject'),


    # Staff
    path("staff/home/", views.staff_home, name='staff_home'),
    path("staff/apply/leave/", views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", views.staff_feedback, name='staff_feedback'),
    # path("staff/view//", views.staff_view_profile,
    #      name='staff_view_profile'),
    path("staff/attendance/take/", views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_students/", views.get_students, name='get_students'),
    path("staff/attendance/fetch/", views.get_student_attendance,
         name='get_student_attendance'),
    path("staff/attendance/save/",
         views.save_attendance, name='save_attendance'),
    path("staff/attendance/update/",
         views.update_attendance, name='update_attendance'),
    path("staff/fcmtoken/", views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", views.staff_add_result, name='staff_add_result'),
    # path("staff/result/edit/", EditResultView.as_view(),
    #      name='edit_student_result'),
    path('staff/result/fetch/', views.fetch_student_result,
         name='fetch_student_result'),



    # Student
    path("student/home/", views.student_home, name='student_home'),
    path("student/view/attendance/", views.student_view_attendance,
         name='student_view_attendance'),
    path("student/apply/leave/", views.student_apply_leave,
         name='student_apply_leave'),
    path("student/feedback/", views.student_feedback,
         name='student_feedback'),
    # path("student/view/profile/", views.student_view_profile,
    #      name='student_view_profile'),
    path("student/fcmtoken/", views.student_fcmtoken,
         name='student_fcmtoken'),
    path("student/view/notification/", views.student_view_notification,
         name="student_view_notification"),
    path('student/view/result/', views.student_view_result,
         name='student_view_result'),

]
